app/main/models.py
import peewee as pw
from app.database import database
import pandas as pd
import datetime
from math import ceil
import app.helpers as hlp


@database.func('lowercase_search')
def lowercase_search(name, filter):
    return filter.lower() in name.lower()


@database.func('synonyms_search')
def synonyms_search(target, filter):
    return Product.is_in_synonyms(target, filter)


class BaseModel(pw.Model):
    class Meta:
        database = database


class Catalogue(BaseModel):
    pass


class Price(BaseModel):
    date = pw.DateField(formats=['%Y-%m-%d'], default=datetime.datetime.now)


class Owner(BaseModel):
    id = pw.PrimaryKeyField()
    name = pw.CharField()
    address = pw.CharField()
    contact = pw.CharField()

    class meta:
        table_name = 'owners'


class Product(BaseModel):
    class meta:
        table_name = 'products'

    name = pw.CharField()
    code = pw.CharField(null=True)
    price = pw.FloatField(null=True)
    photo = pw.CharField(null=True)
    content = pw.TextField(null=True)
    synonyms = {"bosch": ("bosh",
                          "b0sh",
                          "b0sch",
                          "бош",
                          "вош",
                          "б0ш",
                          "в0ш",
                          ",ji",
                          ",0i",
                          "dji"),
                "denso": ("денсо", "дэнсо", "ltycj"),
                "dens": ("денс", "дэнс", "l'yc", "ltyc"),
                "den": ("ден", "дэн", "l'y", "lty"),
                "delphi": ("делфи",
                           "дэлфи",
                           "делфай",
                           "дэлфай",
                           "дэлфу",
                           "делфу",
                           "l'kab",
                           "ltkab",
                           "ltkafq",
                           "ltkae",
                           "l'kae"),
                "delph": ("делф", "дэлф", "делфй"),
                "delp": ("делф", "дэлф", "делфй"),
                "ямз": ("zvp", "zmp", "yamz"),
                "камаз": ("rfvfp", "камас", "kamaz", "kamas"),
                "кама": ("kama", "rfvf"),
                "кам": ("kam", "rfv"),
                "ford": ("форд", "форт", "ajhn", "ajhl"),
                "man": ("ман", "мэн", "vfy"),
                "toyota": ("тойота",
                           "тоета",
                           "тоёта",
                           "njqjnf",
                           "njtnf",
                           "nj`nf"),
                "scania": ("скания", "сканья", "сканя", "crfybz", "crfymz"),
                "renault": ("рено", "ренно", "рэно", "reno", "htyj"),
                "mercedes": ("мерседес",
                             "мэрседес",
                             "мэрсэдес",
                             "мэрсэдэс",
                             "мерсэдес",
                             "мерседэс",
                             "мерс",
                             "мерсед",
                             "vthc",
                             "mersedes",
                             "mersed",
                             "mers"),
                "daw": ("даф", "дав", "dav", "daf", "lfa", "lfd"),
                "peugeot": ("пежо",
                            "пижо",
                            "pegeot",
                            "peguot",
                            "peugeo",
                            "gt;j",
                            "gb;j"),
                "тнвд": ("tnvd", "nydl")}

    @staticmethod
    def is_in_synonyms(target, filter):
        '''
        Решает проблему с русскими буквами (заглавными, строчными)
        при поиске в SQlite, не поддерживающим COLLOCATION NOCASE
        А также делает поиск по синонимам, т.е. обрабатывает опечатки
        при вводе в графе поиска.
        Функция вызывается в запросе к БД через Peewee ORM
        '''
        filter = filter.lower()
        target = target.lower()
        synonyms = Product.synonyms
        for s_key in synonyms.keys():
            if (filter in synonyms[s_key] or filter == s_key):
                filter = s_key
                break

        return filter in target

    @staticmethod
    def convert_bad_synonym_to_good_phrase(phrase=''):
        '''
        Это нужно, чтобы после неудачного ввода, напр. "мэрсэдэс",
        пользователь увидел на странице "Поиск по запросу mercedes"
        При этом в исходном csv-файле, все марки и брэнды должны быть
        приведены к правильным английским названиям: Bosch, Renault, Toyota
        '''
        synonyms = Product.synonyms
        for s_key in synonyms.keys():
            if (phrase in synonyms[s_key] or phrase == s_key):
                phrase = s_key
                break
        return phrase


class Brand(BaseModel):
    class meta:
        table_name = 'brands'

    brand_name = pw.CharField(unique=True)


class ProductBrand(BaseModel):
    class Meta:
        indexes = (
            (('brand_id', 'product_id'), True)
        ),
        table_name = 'products_brands'

    brand_id = pw.ForeignKeyField(Brand, backref='product_brand')
    product_id = pw.ForeignKeyField(Product, backref='product_brand')


class Pagination(object):
    def __init__(self, page, per_page, total_count):
        self.page = page
        self.per_page = per_page
        self.total_count = total_count

    @property
    def pages(self):
        return int(ceil(self.total_count / float(self.per_page)))

    @property
    def has_prev(self):
        return self.page > 1

    @property
    def has_next(self):
        return self.page < self.pages

    def iter_pages(self, left_edge=2, left_current=2,
                   right_current=2, right_edge=2):
        last = 0
        for num in range(1, self.pages + 1):
            if num <= left_edge or (num > self.page - left_current - 1 and
               num < self.page + right_current) or \
               num > self.pages - right_edge:
                    if last + 1 != num:
                        yield None
                    yield num
                    last = num

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__, template_folder='templates')

from . import views

app/main/views.py
import re
import peewee as pw
import urllib
from flask import (
    render_template,
    request,
    session,
    send_from_directory,
    json,
    make_response,
    send_file
)
from ..main import main
from .models import (
    Product,
    Brand,
    ProductBrand,
    Price,
    Pagination
)

'''
import logging
logger = logging.getLogger('peewee')
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)
'''


@main.route('/', methods=['GET'])
def index():
    ordered_list = session.get('ordered_list')
    return render_template('home.html', ordered_list=ordered_list)


@main.route('/favicon.ico')
def favicon():
    return send_file('favicon.ico')


@main.route('/product/<int:id>', methods=['GET'])
def product(id):
    ordered_list = session.get('ordered_list')
    product = (Product().select(Product, Brand.brand_name)
                        .join(
                            ProductBrand, 'LEFT',
                            on=(ProductBrand.product_id == Product.id))
                        .switch(Product)
                        .join(
                            Brand, 'LEFT',
                            on=(Brand.id == ProductBrand.brand_id))
                        .where(Product.id == id)
                        .get())
    return render_template('product.html',
                           product=product,
                           ordered_list=ordered_list)


@main.route('/about', methods=['GET'])
def about():
    ordered_list = session.get('ordered_list')
    return render_template('about.html', ordered_list=ordered_list)


@main.route('/delivery', methods=['GET'])
def delivery():
    ordered_list = session.get('ordered_list')
    return render_template('delivery.html', ordered_list=ordered_list)


@main.app_template_filter('is_alpha_numeric')
def is_alpha_numeric(str=''):
    return bool(re.match('^(?=.*[0-9]$)|(?=.*[a-zA-Z])', str))


@main.route('/catalogue/', defaults={'page': 1})
@main.route('/catalogue/search/<filter>', defaults={'page': 1})
@main.route('/catalogue/page/<int:page>')
@main.route('/catalogue/search/<filter>/page/<int:page>')
def catalogue(page=1, filter=''):
    ordered_list = session.get('ordered_list')
    filter = urllib.parse.unquote(filter)
    products_per_page = 10
    if len(filter) > 0:
        decoded = urllib.parse.unquote(filter)
        '''
        Comment the following stroke because it case sensitive
        products = Product.select().where(Product.name.contains(filter))
            .paginate(
                page, products_per_page
            )
        add lowercase_search() to make search case insensitive.
        See @database.func('lowercase_search') in model.py
        '''
        products = Product().select().where(
            pw.fn.synonyms_search(Product.name, decoded)).paginate(
                page, products_per_page)
        total_products = Product.select().where(
            pw.fn.synonyms_search(Product.name, decoded)).count()
    else:
        products = Product.select().paginate(page, products_per_page)
        total_products = Product.select().count()

    # Get price date
    price_query = Price.select(pw.fn.MAX(Price.date)).scalar()
    if price_query is not None:
        price_date = price_query.strftime('%d.%m.%Y')
    else:
        price_date = '18.10.2018'

    pagination = Pagination(page, products_per_page, total_products)
    filter = Product.convert_bad_synonym_to_good_phrase(filter)

    return render_template(
        'catalogue.html',
        price_date=price_date,
        pagination=pagination,
        products=products,
        page=page,
        filter=filter,
        ordered_list=ordered_list)


@main.route('/dist/<path:path>')
def static_dist(path):
    # тут пробрасываем статику
    return send_from_directory("static/js/dist", path)


@main.route('/api/search/<phrase>')
def search_result(phrase):
    decoded = urllib.parse.unquote(phrase)
    query = Product().select().where(pw.fn.synonyms_search(
        Product.name, decoded))
    output = {}
    output['results'] = []

    for result in query:
        output['results'].append({'name': result.name})

    return json.dumps(output, ensure_ascii=False)


@main.route('/api/session', methods=["POST"])
def save_selected_product_to_session():
    if request.method == 'GET':
        return make_response('failure')
    if request.method == 'POST':
        id = request.get_json().get('id')
        command = request.get_json().get('command')
        if 'ordered_list' not in session:
            session['ordered_list'] = []
        ordered_list = session['ordered_list']
        # add to shop basket list
        if 'add' in command and id not in ordered_list:
            ordered_list.append(id)
        # remove from shop basket list
        if 'remove' in command:
            ordered_list.remove(id)

        session['ordered_list'] = ordered_list
        params = {
            'result': session['ordered_list']
        }
    return json.dumps(params)


@main.app_errorhandler(404)
def handle_404(err):
    return render_template('404.html'), 404


'''
@main.app_errorhandler(500)
def handle_500(err):
    return render_template('500.html'), 500
'''

app/main/templates/about.html
{% extends "layout.html" %}
{% block content %}
<div id="app">
    <!-- Buefy components goes here -->
</div>
<div id="app2">
    <label>{{selectedEvent}}</label>
    <vue-instant :suggestion-attribute="suggestionAttribute" v-model="value" :disabled="false"  @input="changed" @click-input="clickInput" @click-button="clickButton" @selected="selected"  @enter="enter" @key-up="keyUp" @key-down="keyDown" @key-right="keyRight" @clear="clear"  @escape="escape" :show-autocomplete="true" :autofocus="false" :suggestions="suggestions" name="customName" placeholder="custom placeholder" type="google"></vue-instant>
</div>

{% endblock %}

app/main/templates/catalogue.html
{% extends "layout.html" %}
{% from "macros.html" import render_pagination %}
{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/catalogue.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
    <section class="hero">
        <div class="hero-body">
            <div id="catalog" class="container is-widescreen">
                {% if filter|length() > 0 %}
                    <div class="content">
                        <blockquote>
                            <div class="columns is-mobile">
                                <div class="column  is-narrow">
                                    <span class="icon">
                                        <i class="mdi mdi-magnify mdi-48px" style="color: lightgrey; margin-top:10px;"></i>
                                    </span>
                                </div>
                                <div class="column">
                                    <p>Результаты поиска по строке: <strong>{{ filter }}</strong>                                            </p>
                                    <div id="reset_search" class="container">
                                        <section>
                                            <b-field>
                                                <b-checkbox-button v-model="checkboxGroup"
                                                        native-value="Nop"
                                                        type="is-danger">
                                                    <b-icon icon="close"></b-icon>
                                                    <span>Сбросить фильтрацию</span>
                                                </b-checkbox-button>
                                        </section>
                                    </div>
                                </div>
                            </div>
                        </blockquote>
                    </div>
                {% endif %}

                <div id="product_list">
                    {% for product in products %}
                        <!-- Main container -->
                        <nav class="level">
                            <!-- Left side -->
                        <div class="level-left">
                                <div class="level-item">
                                        <figure class="media-left">
                                            <p class="image is-96x96" style="height: 74px;">
                                                <a href="{{ url_for('main.product', id=product['id']) }}">
                                                    <img src="{{ url_for('static', filename='img/products/1.jpg') }}">
                                                </a>
                                            </p>
                                        </figure>
                                </div>
                                <div class="level-item">
                                    <div class="subtitle is-5">
                                        <p><strong><a href="{{ url_for('main.product', id=product['id']) }}">{% if valid_code %}{{ splitted_title[1] }} {{ splitted_title[0] }}{% else %}{{ product.name }}{% endif%}</a></strong></p>
                                        <p class="subtitle is-6">
                                            {% if product.code %}
                                                Код запчасти: {{ product.code }} 
                                            {% endif %}
                                            Производитель: Bosch
                                        </p>
                                    </div>
                                </div>
                            </div>
                        
                            <!-- Right side -->
                            <add-order-button :id="{{ product.id }}" inline-template>
                                <div>
                                    <div class="level-right">
                                        <div class="level-item">
                                            <div class="title is-5">{{ '{:,.0f}'.format(product['price']|int()).replace(","," ") }} руб.
                                                <p class="subtitle is-7 show_price" v-bind:class="{'yes': checked }">Цена на {{ price_date }}</p>
                                            </div>
                                        </div>
                                        <a v-cloak class="button is-rounded" @click.prevent="toggleActivity({{ product.id }})" v-bind:class="{ 'is-success': checked }">
                                            <span>[[ activity ]]</span>
                                            <span class="icon is-small">
                                                <i class="mdi mdi-check mdi-18px" v-bind:class="{ 'mdi-24px': checked }"></i>
                                            </span>
                                        </a><br />
                                        <a href="#" class="content is-small goto_order" v-bind:class="{'yes': checked }">Оформить заявку</a>
                                    </div>
                                </div>
                            </add-order-button>
                        </nav>
                    {% endfor %}
                </div>
                {{ render_pagination(pagination, page, filter) }}
            </div>
        </div>
    </section> 
{% endblock %}

{% block javascript %}
    {{ super() }}
    <script src="https://unpkg.com/buefy/dist/components/checkbox"></script>
    <script src="{{ url_for('static', filename='js/catalogue.js') }}" ordered_list="{{ ordered_list }}"></script>
{% endblock %}

app/main/templates/delivery.html
{% extends "layout.html" %}
{% block content %}

{% endblock %}

app/main/templates/home.html
{% extends "layout.html" %}
{% block content %}
<h1>Hello from Home with reloading</h1>
<div id="app">
        <!-- Buefy components goes here -->
</div>
{% endblock %}
{% block javascript %}
    {{ super() }}
    
{% endblock %}

app/main/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/buefy/dist/buefy.min.css">
    <!--<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>//-->
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.6/css/all.css">//-->
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">//-->
    <!--<link rel="stylesheet" href="https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css">//-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css" rel="stylesheet">
    <style>
        
    </style>
    {% endblock %}
</head>

<body>
    <section class="hero is-info">
        <div class="hero-body">
            <div class="columns">
                <div class="column">
                    <p class="title">input is-rounded
                        LOGO
                    </p>
                    <p class="subtitle">
                        Каталог топливной аппаратуры
                    </p>
                </div>
                <div class="column">
                    <p class="title">ТЕЛЕФОН</p>
                    <p class="subtitle">С 8:00 до 20:00, время московское</p>
                    <p class="subtitle>">Email: usm12@mail.ru</p>
                </div>
                <div class="column">
                    <p class="title">Напишите нам</p>
                </div>
                <div class="column">
                    <div id="shop_basket">
                        <shop-basket inline-template>
                            <div>
                                <p class="title">Список заказа</p>
                                <p class="subtitle>"><a href="">Товаров: [[products_num]]</a></p>
                            </div>
                        </shop-basket>
                    </div>
                </div>
            </div>
        </div>
    </section> 
    <nav class="navbar is-black">
        <div class="navbar-brand">
            <a class="navbar-item is-hidden-touch" href="#">ДИЗЕЛЬ СКЛАД:</a>
            <div id="autocomplete_search" style="margin: 8px 20px 0 20px;">
                    <section>
                        <b-field>
                            <b-autocomplete
                                type="search"
                                icon="magnify"
                                v-model="name"
                                :data="data"
                                placeholder="например, denso"
                                field="title"
                                @keyup.native="getAsyncData"
                                @select="option => selected = option">
                                
                                <template slot-scope="props">
                                    <div class="media">
                                        <div class="media-content">
                                            [[ props.option ]]
                                        </div>
                                    </div>
                                </template>
                            </b-autocomplete>
                            <p class="control">
                                    <button class="button is-primary" onclick="window.location = '/catalogue/search/' + app.name;">Поиск</button>
                                </p>
                        </b-field>
                    </section>
                </div>
            <div class="navbar-burger burger" data-target="navMenuColorblack-example">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenuColorblack-example" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{{ url_for('main.index') }}">
                    Главная
                </a>
                <a class="navbar-item" href="{{ url_for('main.catalogue') }}">
                    Каталог
                </a>
                <a class="navbar-item" href="{{ url_for('main.delivery') }}">
                    Оплата и доставка
                </a>
                <a class="navbar-item" href="{{ url_for('main.about') }}">
                    О компании
                </a>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <section class="hero is-dark">
        <div class="hero-body">
                <p>
                    <strong>АСЦТА</strong> Ассоциация сервисных центров топливной аппаратуры.
                </p>
        </div>
    </section>

    {% block javascript %}
    <!-- <script src="/static/js/vue.min.js"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script src="https://unpkg.com/buefy/dist/components/autocomplete"></script>
    <script src="https://unpkg.com/buefy/dist/components/field"></script>
    <script src="https://unpkg.com/buefy/dist/components/tabs"></script>
    <script src="https://unpkg.com/buefy/dist/components/icon"></script>
    <script src="https://unpkg.com/axios@0.15.3/dist/axios.min.js"></script>
    <script src="{{ url_for('static', filename='js/bus.js') }}"></script>
    <script src="{{ url_for('static', filename='js/layout.js') }}" ordered_list="{{ ordered_list }}" filter="{{ filter }}"></script>
    {% endblock %}
</body>
</html>

app/main/templates/macros.html
{% macro render_pagination(pagination, page, filter) %}
    <nav class="pagination is-centered is-rounded" role="navigation" aria-label="pagination">
        {% if pagination.has_prev %}
            {% if filter|length() > 0 %}
                <a class="pagination-previous" href="/catalogue/search/{{ filter }}/page/{{ page - 1 }}">Prev</a>
            {% else %}
                <a class="pagination-previous" href="/catalogue/page/{{ page - 1 }}">Prev</a>
            {% endif %}
        {% endif %}
        <ul class="pagination-list">
        {%- for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                    {% if filter|length() > 0 %}
                        <li><a class="pagination-link" aria-label="Goto page {{ page }}" href="/catalogue/search/{{ filter }}/page/{{ page }}">{{ page }}</a></li>
                    {% else %}
                        <li><a class="pagination-link" aria-label="Goto page {{ page }}" href="/catalogue/page/{{ page }}">{{ page }}</a></li>
                    {% endif %}
                {% else %}
                    <li><a class="pagination-link is-current" aria-label="Page {{ page }}" aria-current="page">{{ page }}</a></li>
                {% endif %}
            {% else %}
                <li><span class="pagination-ellipsis">&hellip;</span></li>
            {% endif %}
        {%- endfor %}
        </ul>
        {% if pagination.has_next %}
            {% if filter|length() > 0 %}
                <a class="pagination-previous" href="/catalogue/search/{{ filter }}/page/{{ page + 1 }}">Next &raquo;</a>
            {% else %}
                <a class="pagination-previous" href="/catalogue/page/{{ page + 1 }}">Next &raquo;</a>
            {% endif %}
        {% endif %}
    </div>
{% endmacro %}

app/main/templates/paginate.html
<nav class="pagination is-centered is-rounded" role="navigation" aria-label="pagination">
        {% if page > 1 %}
            <a class="pagination-previous">Previous</a>
        {% endif %}
        {% if page < total_items / items_per_page %}
            <a class="pagination-next">Next page</a>
        {% endif %}
        <ul class="pagination-list">
            {% for p in total_items / items_per_page %}
            <li><a class="pagination-link" aria-label="Goto page 1" src="1">1</a></li>
            <li><span class="pagination-ellipsis">&hellip;</span></li>
            <li><a class="pagination-link" aria-label="Goto page 45">{% </a></li>
            <li><a class="pagination-link is-current" aria-label="Page 46" aria-current="page">46</a></li>
            <li><a class="pagination-link" aria-label="Goto page 47">47</a></li>
            <li><span class="pagination-ellipsis">&hellip;</span></li>
            <li><a class="pagination-link" aria-label="Goto page 86">86</a></li>
        </ul>
    </nav>

app/main/templates/populate.html
{% extends "layout.html" %}
{% block content %}

<section class="hero">
    <div class="hero-body">
        <div class="container is-widescreen">
            <div id="populating">
                <run-populating inline-template>
                        <a class="button is-link is-rounded" @click="runPopulating" v-bind:class="{ 'is-loading': checked }">Начать</a>
                        <span v-cloak>
                            [[ run_status ]]
                        </span>
                </run-populating>
            </div>
        </div>
    </div>
</section>
    
{% endblock %}
{% block javascript %}
    {{ super() }}
    <script src="https://unpkg.com/buefy/dist/components/icon"></script>
    <script src="{{ url_for('static', filename='js/jobs.js') }}" run_status="{{ run_status }}"></script>
{% endblock %}

app/main/templates/product.html
{% extends "layout.html" %}
{% block head %}
    {{ super() }}
    <style>
        .hero .tabs ul {
            border-bottom: 1px solid #dbdbdb;
        }
        .b-tabs .tab-content {
            border-left: 1px solid #dbdbdb;
            border-right: 1px solid #dbdbdb;
            border-bottom: 1px solid #dbdbdb;
        }
        .image img {
            max-width: 100%;
            width: auto;
        }
        .material-icons {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            vertical-align: bottom;
            padding-top: 18px;
        }
        .material-icons.md-36 { font-size: 36px; }
        .level-left .level-item:not(:last-child), .level-right .level-item:not(:last-child) {
            margin-right: 2.75rem;
        }
    </style>
{% endblock %}
{% block content %}

<section class="hero">
    <div class="hero-body">
        <div class="container is-widescreen">
            <div class="columns">
                <div class="column is-3">
                    <img src="{{ url_for('static', filename='img/units/pic.jpg') }}" }}>
                </div>
                <div class="column">
                    <h1 class="title is-spaced">{{ product['name'] }}</h1>

                    <nav class="level">
                        <!-- Left side -->
                        <div class="level-left">
                            <div class="level-item">
                                <h2 class="subtitle is-6" style="white-space: nowrap;">
                                    <i class="material-icons md-36">local_offer</i>
                                    <span class="is-size-4 has-text-weight-bold">{{ '{:,.0f}'.format(product['price']|int()).replace(","," ") }} руб.</span>
                                </h2>
                            </div>
                            <div class="level-item">
                                <div>
                                    <p class="heading">Цена актуальна</p>
                                    <p class="title is-6">13.08.2018 г.</p>
                                </div>
                            </div>
                        </div>
                        <!-- Right side -->
                        <div class="level-right">
                            {% if (product.brand is defined) and (product.brand.brand_name is defined) %}
                                <div>
                                    <p class="heading">Производитель</p>
                                    <p class="title is-6">{{ product['brand']['brand_name'] }}</p>
                                </div>
                            {% endif %}
                        </div>
                      </nav>
                    <div id="item_tabs" class="">
                        <section>
                            <b-tabs type="is-boxed" :animated="false">
                                <b-tab-item label="Описание" icon="google-photos">
                                    <p>
                                        {{ product['content'] }} Турбокомпрессор 1118100-ED01A Turbocharger 53039700168  BorgWarner. Применяется для двигателей 4D20 автомобилей  Great Wall Hover H5
                                        
                                    </p>
                                </b-tab-item>
                                <b-tab-item label="Оплата" icon="library-music"></b-tab-item>
                                <b-tab-item label="Доставка" icon="video">
                                    <p>
                                        Оплата по счету с НДС. Работаем со всеми регионами России. Звоните!
                                    </p>
                                </b-tab-item>
                            </b-tabs>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



    
{% endblock %}

{% block javascript %}
    {{ super() }}
    <script>
        const item_tabs = new Vue()
        item_tabs.$mount('#item_tabs')       
    </script>
{% endblock %}